export const MAIN = '#1ABC9C'
export const TEXT = '#4B4B4B'
export const LIGHT_TEXT = '#D1D1D1'
export const BACKGROUND_GRAY = '#EAF0F2' // '#F5F5F7'
export const TINT = '#34495E'
export const IOS_FONT = 'Chalkboard SE'
