// Auth type constants
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCEEDED = 'LOGIN_USER_SUCCEEDED'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'
// Post type constants
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCEEDED = 'CREATE_POST_SUCCEEDED'
export const CREATE_POST_MODAL_VISIBLE = 'POST_MODAL_VISIBLE'
export const GET_POST_REQUEST = 'GET_POST_REQUEST'
